Спринт 11 - первая версия
pnikishechkin/filmorate pull request #2
Opened 2024-07-30 18:47 UTC by pnikishechkin

2024-07-30 23:38 UTC, TomattmanYandex requested changes
Привет, пулл реквест не прошел все проверки, без этого принять нельзя
еще и парочка комментов есть  будут много где однотипные, в остальных сервисах и контроллерах, так что надо исправлять

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
так как вы используете ломбук можно вместо того чтобы писать руками конструктор, можно использовать аннотацию @RequiredArgsConstructor

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
обычно в контроллер не добавляют зависимость от репозитория, контроллер зависит от сервиса, сервис зависит от хранилища

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.addFilm(film);
аналогично, на уровне сервиса метод который может сразу проверять и добавлять в хранилище

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            count = 10;
лучше использовать фигурные скобки даже если одна команда, так читается лучше

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopular(@PathVariable Integer count) {
вместо того чтобы делать дополнительные проверки, можно установить дефолтное значение

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    boolean containsFilmById(Integer id);
вместо того чтобы делать проверку так, можно сделать следующим образом
Film getFilmById(Integer id); сделать чтобы возвращал Optional<Film>
и вместо этого метода получаем, и проверяем пустой он или нет

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
можно так же через ломбук инициализировать

2024-07-30 23:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.containsFilmById(filmId)) {
если не найден фильм то стоит кидать ошибку

2024-07-31 08:25 UTC, pnikishechkin commented
Привет! Да, вчера была однозначно преждевременная отправка. Исправил все замечания, все тесты работают, обработку исключений также добавил.

2024-07-31 21:02 UTC, TomattmanYandex approved these changes
Принято, но обрати внимание на то что прокоментировал

2024-07-31 21:02 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.containsFilmById(film.getId())) {
если сделатьь как я рекомендовал, чотбы возвращался Optional то можно было бы сделать гораздо красивее и лаконичнее
filmStorage.getFilmById(id).orElseThrow(/*тут создать ошибку*/)

2024-08-07 11:47 UTC, merged