Спринт 13
pnikishechkin/filmorate pull request #26
Opened 2024-09-12 21:22 UTC by pnikishechkin

2024-09-12 22:19 UTC, tomattman requested changes
Привет, отличная работа, по самому коду, вопрос только к групповой составляющей, а именно к отсутствию общего стиля кода
Во всем остальном идеальная работа

Еще один момент который тоже важный, но он больше организационный
Должен быть readme файл, с описанием того какие задачи выполняла группа
Рекомендую расписать чуть больше деталей по каждой из них

2024-09-12 22:19 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +     */
Класс очень выделяется стилем оформления
Обычно на проектах все разработчики стараются придерживаться одного стиля, так по коду легче ориентироваться и понимать,
Рекомендую привести все к одному виду

2024-09-12 22:19 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Boolean deleteReview(@Positive @PathVariable Integer id) {
это даже в глаза бросается на уровне порядка аннотаций)))
Но это совсем уж мелочи

2024-09-12 22:19 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public enum EventType {
чаще такое все же выносят из класса, добавляют отдельным файлом

2024-09-12 22:19 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +
и снова совершенно другой стиль

2024-09-12 22:19 UTC, tomattman commented on src/main/resources/data.sql
> +/* Тестовые данные */
закомментированный код не оставляем

2024-09-13 00:08 UTC, vpopi4 commented on src/main/resources/data.sql
> +/* Тестовые данные */
Это не закоментированный код

2024-09-14 11:16 UTC, tomattman approved these changes
Принято

2024-09-26 08:22 UTC, pnikishechkin commented
@tomattman , поставь пожалуйста ревью, чтобы можно было закрыть ПР

2024-10-02 11:07 UTC, rossanatotolo approved these changes

2024-10-02 11:30 UTC, merged