Реализация ТЗ спринт №12
pnikishechkin/filmorate pull request #3
Opened 2024-08-22 16:12 UTC by pnikishechkin

2024-08-23 09:31 UTC, tomattman requested changes
Привет, хорошая работа, я оставил в комментариях места где надо в обязательном порядке уменьшить количество запросов

2024-08-23 09:31 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/base/BaseDbRepository.java
> +//    protected long insert(String query, MapSqlParameterSource params) {
закомментированный код не допускается

2024-08-23 09:31 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Получаем все фильмы с включенными данными рейтинга
для получения n фильмов если в базе m жанров будет сделано n * m + 1 запрос в базу надо чтобы в любом случае было максимум три запроса, можно сделать даже в 2

2024-08-23 09:31 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Альтернативное решение: записываем список объектов жанров для каждого фильма из базы
закомментированный код не допускается и этот вариант оптимальнее, ибо не понятно, зачем нам получать список жанров, чтобы потом все равно получать список жанров

2024-08-23 09:31 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Добавление связей фильма с жанрами
снова закомментированный код

2024-08-23 09:31 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Редактирование предполагает, что в запросе пришли данные с новыми жанрами фильма?
вообще думаю что да логично давать возможность обновить жанры

2024-08-23 09:31 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getGenres() != null) {
тут можно подумать тоже над уменьшением количества запросов, но тут уже не обязательно

2024-08-23 10:40 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Получаем все фильмы с включенными данными рейтинга
Не совсем понял, почему количество запросов (n * m + 1) ?

Я делаю так:
1. Мы получаем список всех фильмов (1 запрос)
2. Получаем список всех жанров (1 запрос)
3. Для каждого фильма получаем список идентификаторов его жанров (n запросов - по количеству фильмов)
4. Заполняем множество жанров для каждого фильма, найдя нужные объекты в ранее полученном списке (0 запросов)

Получается, количество запросов равно (n + 2)

2024-08-23 10:44 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Альтернативное решение: записываем список объектов жанров для каждого фильма из базы
В данном случае предлагается сделать:

1. Получаем список всех фильмов (1 запрос)
2. Для каждого фильма получаем целые объекты с описанием его жанров (n запросов - по количеству фильмов)

Получаем n + 1 запрос, но объем передаваемых данных больше, т.к. мы многократно получаем пакеты с полным описанием жанров.

Какой из вариантов в итоге более предпочтительный?

2024-08-23 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Получаем все фильмы с включенными данными рейтинга
setGenres(genres.stream().filter()...
для каждого фильма в стриме перебираются все жанры, отсюда и берется m * n 
и в любом случае, даже n + 2 много, должно быть просто 2 или 3

2024-08-23 11:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Альтернативное решение: записываем список объектов жанров для каждого фильма из базы
должно быть константное вне зависимсоти от количества фильмов

2024-08-23 13:15 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Получаем все фильмы с включенными данными рейтинга
Идею я понял, на вебинаре говорили о том, что можно сделать один общий запрос и ResultSetExtractor.
Но говорилось и о том, что правильнее и оптимальнее делать в несколько запросов, при этом будем оперировать мЕньшим объемом данных, вот скриншот этого алгоритма с вебинара:
![2024-08-23_16-14-52](https://github.com/user-attachments/assets/aa00d69e-4ef1-46ad-a1da-c92ae758d1f8)

2024-08-26 11:20 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Получаем все фильмы с включенными данными рейтинга
Сделал, фиксированно 3 запроса

2024-08-26 11:20 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Альтернативное решение: записываем список объектов жанров для каждого фильма из базы
Сделал

2024-08-26 11:20 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Добавление связей фильма с жанрами
убрал

2024-08-26 11:21 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        // Редактирование предполагает, что в запросе пришли данные с новыми жанрами фильма?
Сделал обновление жанров

2024-08-26 11:22 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getGenres() != null) {
уменьшил количество запросов, аналогично

2024-08-26 11:25 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getGenres() != null) {
уменьшил, проверка на жанры теперь через 1 запрос выполняется

2024-08-26 13:30 UTC, tomattman approved these changes
Привет, оставил пару комментариев на улучшение, но это так, к сведению

2024-08-26 13:30 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +    private List<Film> getSomeFilms(String query, Map<String, Object> map) {
очень мне не нравится имя метода, воспринимается как какая то затычка, лучше в таких случая делать просто либо через перегрузку либо просто getFilms

2024-08-26 13:30 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        List<Genre> genres = genreDbRepository.getAll();
можно было сделать  еще лучше
SQL_GET_FILMS_GENRES
сделать чтобы возвращал filmId, genreId, genreName через join и тогда было бы на один запрос меньше, и логика бы осталась примерно такая же

2024-08-26 14:21 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +    private List<Film> getSomeFilms(String query, Map<String, Object> map) {
Ок, хорошо)

2024-08-26 14:24 UTC, pnikishechkin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbRepository.java
> +        List<Genre> genres = genreDbRepository.getAll();
Для получения одного фильма (метод getById) я так и сделал, через 1 запрос с join к genres. 
Для получения всех фильмов сделал через 3 запроса, но при этом я же получаю сильно меньший объем данных, разве не так? Поскольку если представить, что фильмов огромное количество, и у каждого из них еще несколько жанров, то мы получаем много лишней информации. 
Об этом также говорил Владимир на вебинаре, что можно сделать через Join, но более оптимальнее через общие запросы:
![image](https://github.com/user-attachments/assets/7013d27c-772c-4829-8e98-485d82677e4d)

2024-09-02 14:38 UTC, merged